#this require wl-clipborad package
theme = "gruvbox_dark_hard" 

[editor]
line-number = "absolute"
mouse = true
true-color = true
bufferline = "always" 
cursorline = true
color-modes = true
clipboard-provider = "wayland"
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false 

[editor.soft-wrap]
enable = true 
[editor.indent-guides]
render = true 

[editor.lsp]
display-messages = true 
display-inlay-hints = true 
snippets = true

[keys.normal]
"c" = "split_selection_on_newline"
"esc" = "@,"
